apps/aluno/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.core import views
from . import views

app_name = 'aluno'


urlpatterns = [
    # Add a view do core
    path('',views.HomeView.as_view(),name='home'),
    path('novo/',views.AddAluno,name='add_aluno'),
    path('lista/',views.ListAlunosView.as_view(),name='lista_alunos'),
    path('editar/<int:id_aluno>/',views.edit_aluno,name='edit_aluno'),
    path('delete/<int:id_aluno>/',views.deleteAluno,name='delete_aluno'),
]

apps/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

# Chamar a view.
urlpatterns = [
    path('', views.home, name='home'),
]

apps/professor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

campus/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.core import views
from apps.aluno import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Fazer uma rota de campus para core.
    path('', include('core.urls', namespace='core')),
    # Rotas do core para os apps.
    path('aluno/', include('aluno.urls', namespace='aluno'))
]

apps/aluno/models.py
from django.db import models
from django.contrib.auth.models import User

class Aluno(models.Model):
    nome = models.CharField(max_length=100,help_text='Nome do Aluno')
    cpf = models.CharField(max_length=12,help_text='CPF do Aluno',blank=False,default='')
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='perfil',default='')
    email = models.CharField(max_length=100,help_text='e-mail',default='')
    data_nasc = models.DateField('Data de Nascimento',auto_now=False,auto_now_add=False,blank=True,default='')

class Meta:
    ordering=['-id']

def __str__(self):
    return self.nome

apps/core/models.py
from django.db import models

# Create your models here.

apps/professor/models.py
from django.db import models

# Create your models here.
class Professor(models.Model):
    nome = models.CharField(max_length=100, help_text='Nome do professor')

apps/turma/models.py
from django.db import models

# Create your models here.

apps/aluno/forms.py
from django import forms
from aluno.models import Aluno

class AlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        # fields = ['nome','cpf','email','data_nasc','user']
        fields = '__all__'
        

apps/aluno/views.py
from django.shortcuts import render,redirect, get_list_or_404,get_object_or_404
from aluno.models  import Aluno
from django.contrib import messages
from aluno.forms import AlunoForm
from django.views.generic import TemplateView, ListView

class HomeView(TemplateView):
   template_name = 'aluno/lista_alunos.html'

class ListAlunosView(ListView):
   model = Aluno
   template_name = 'aluno/lista_alunos.html'
   context_object_name = 'alunos'
   paginate_by = 6
   def get_queryset(self):
       return Aluno.objects.all().order_by('-id')

def deleteAluno(request, id_aluno):
    aluno = Aluno.objects.get(id=id_aluno)
    aluno.delete()
    messages.success(request, "Aluno deletado com sucesso!")
    return redirect('aluno:lista_alunos')

def edit_aluno(request, id_aluno):
    template_name = 'aluno/add_aluno.html'
    context = {}
    aluno = get_object_or_404(Aluno, pk=id_aluno)
    if request.method == 'POST':
        form = AlunoForm(request.POST, instance=aluno)
        if form.is_valid():
            form.save()
            messages.success(request, "edição salva com sucesso!")
            return redirect('aluno:lista_alunos')
    form = AlunoForm(instance=aluno)
    context['form'] = form
    return render(request, template_name, context)


def AddAluno(request):
    template_name = 'aluno/add_aluno.html'
    context = {}
    if request.method == 'POST':
        form = AlunoForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            form.save()
            messages.success(request, "Aluno salvo com sucesso!")
        else:
            messages.error(request, "Erro de dados!")
    form = AlunoForm()
    context['form'] = form
    return render(request,template_name,context)

apps/core/views.py
from django.shortcuts import render

# Chamar a url para renderizar a página html.
def home(request):
    return render(request, 'base.html', {})

apps/professor/views.py
from django.shortcuts import render

# Create your views here.

apps/turma/views.py
from django.shortcuts import render

# Create your views here.

templates/aluno/add_aluno.html
{% extends 'base.html'%}
{% load widget_tweaks %}

{% block title %}
{{block.super}} - Cadastro de Alunos
{% endblock title %}

{% block body %}

<div class="container">
    {% include 'partials/messages.html' %}
    <div class="row">
        <div class="input-field col s5">
            <div class="form-group">
                <h3>Adicionar Aluno</h3>
            </div>
            <form action="." method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Nome</label>
                    {{ form.nome|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.user.id_for_label }}">Usuário:</label>
                    {{ form.user|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.cpf.id_for_label }}">CPF</label>
                    {{ form.cpf|add_class:"form-control" |attr:"autofocus"}}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-Mail</label>
                    {{ form.email|add_class:"form-control" |attr:"autofocus"}}
                </div>
                <div class="form-group">
                    <label for="form.data_nasc.id_for_label">Data de Nascimento:</label>
                    {{form.data_nasc |add_class:"datepicker"}}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" style="background-color: blueviolet;">Salvar</button>
                    <button type="reset" class="btn btn-primary" style="background-color: blueviolet;">Limpar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/aluno/lista_alunos.html
{% extends 'base.html'%}
{% load widget_tweaks %}

{% block title %}
{{block.super}} - Lista de Alunos
{% endblock title %}

{% block body %}

<div class="container">
    <h2>Alunos</h2>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <!--<th scope="col">#</th>-->
                        <th scope="col">Código</th>
                        <th scope="col">Nome</th>
                        <th scope="col">CPF</th>
                        <th scope="col">User</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% for aluno in alunos %}
                    <tr>
                        <!--<th scope="row">#</th>-->
                        <td>{{ aluno.id }}</td>
                        <td>{{ aluno.nome }}</td>
                        <td>{{ aluno.cpf }}</td>
                        <td>{{ aluno.user }}</td>
                        <td>{{ aluno.email}}</td>
                        <td>
                            <a href="{% url 'aluno:edit_aluno' aluno.id %}" class="btn btn-primary btn-sm" style="background-color: blueviolet;">Editar</a>
                            <a href="{% url 'aluno:delete_aluno' aluno.id %}" class="btn btn-danger btn-sm confirm-delete" style="background-color: blueviolet;" id="deleteButton-{{ aluno.id }}">Excluir</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css' %} " type="text/css" rel="stylesheet" media="screen,projection" />
    <title>Document</title>
</head>

<body >
    <nav class="navbar navbar-dark bg-primary" role="navigation" style="background-color: blueviolet;">
        <div class="nav-wrapper container" style="background-color: blueviolet;"><a id="logo-container" href="/" class="brand-logo" >Django IFCE</a>
            <ul class="right hide-on-med-and-down" style="background-color: blueviolet;">
                <li><a href="">Dashboard</a></li>
                <!-- Dropdown Trigger -->
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown">Aluno<i
                            class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger2" href="#!" data-target="dropdown2">Professor<i
                            class="material-icons right">arrow_drop_down</i></a></li>
                <li><a href="">Sair</a></li>
            </ul>
            <ul id="dropdown" class="dropdown-content">
                <li><a href="{% url 'aluno:add_aluno'  %}">Novo</a></li>
                <li><a href="{% url 'aluno:lista_alunos' %}">Lista</a></li>

                <ul id="nav-mobile" class="sidenav" style="background-color: blueviolet;">
                    <li><a href="">Dashboard</a></li>
                    <li><a href="">Perfil</a></li>
                    <li><a href="">Sair</a></li>
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Dropdown<i
                                class="material-icons right" style="background-color: blueviolet;">arrow_drop_down</i></a></li>
                    <li><a href="">Criar Conta</a></li>
                    <li><a href="">Login</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    {% block body %}

    {% endblock body %}

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });

        let dateObj = new Date();
        //DATEPICKER
        $(document).ready(function () {
            $('.datepicker').datepicker({
                yearRange: [1930, dateObj.getFullYear()],
                format: 'dd/mm/yyyy'
            });
        });
        //NAVBAR DROPDOWN

        //DROPDOWN ALUNO
        $(".dropdown-trigger").dropdown({
            inDuration: 300,
            outDuration: 225,
            constrain_width: false, // Does not change width of dropdown to that of the activator
            hover: false, // Activate on hover
            gutter: 0, // Spacing from edge
            belowOrigin: true, // Displays dropdown below the button
            alignment: 'left' // 
            

        });
        //DROPDOWN PROFESSOR
        $(".dropdown-trigger2").dropdown({
            inDuration: 300,
            outDuration: 225,
            constrain_width: false, // Does not change width of dropdown to that of the activator
            hover: false, // Activate on hover
            gutter: 0, // Spacing from edge
            belowOrigin: true, // Displays dropdown below the button
            alignment: 'center' // 

        });

        /* MODAL*/
        $(document).ready(function () {
            $('.modal').modal();
        });
    </script>
</body>

</html>

templates/partials/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }}" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}